---
- block:
  - name: Add mongodb apt key
    apt_key:
      url: "{{ pritunl_mongodb_apt_key_url }}"
      state: present

  - name: Add an Apt signing key, will not download if present
    apt_key:
      url: "{{ pritunl_mongodb_apt_key_url }}"
      state: present

  - name: Add mongodb apt repository
    apt_repository:
      repo: "{{ pritunl_mongodb_apt_repo }}"
      filename: "mongodb-org-{{ pritunl_mongodb_version }}"
      state: present
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: Check if pritunl is installed
  shell: dpkg -l pritunl | grep '^ii'
  register: pritunl_check_deb
  failed_when: pritunl_check_deb.rc > 1
  changed_when: pritunl_check_deb.rc == 1

- name: Update package lists
  apt: update_cache=yes

- name: Install mongodb
  apt:
    name: mongodb
    state: latest
    update_cache: no
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- block:
  - name: Ensures pritunl dependencies are installed
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: no
    with_items:
      - python
      - net-tools
      - openvpn
      - openssl
      - bridge-utils
      - ca-certificates

  - name: Download and install pritunl v{{ pritunl_version }}
    apt:
      deb: "https://github.com/pritunl/pritunl/releases/download/{{ pritunl_version }}/pritunl_{{ pritunl_version }}-0ubuntu1.focal_amd64.deb"

  when: pritunl_check_deb.rc == 1
